#!/bin/sh


cd build

CONFIGURE=../../jpeg-9d/configure
PREFIX=$(pwd)/../output/

$CONFIGURE --prefix=$PREFIX
make -j8
make install

cd ..

cp -v output/include/* ../../include/jpeglib/
cp -v output/lib/libjpeg.a ../../lib/

echo "finish with libjpeg"
